title: Sebastián RIFFO
email: riffo@geoazur.unice.fr
description: Former postdoctoral fellow 
institution: Géoazur CNRS

twitter_username: ~
github_username: ~
dribbble_username: ~
facebook_username: ~
flickr_username: ~
instagram_username: ~
linkedin_username: ~
pinterest_username: ~
youtube_username: ~
googleplus_username: ~
rss: false

show_excerpts: true
date_format: "%b %-d, %Y"

# logo: https://picsum.photos/123?image=669

# Build settings
# theme: jekyll-theme-strata
# remote_theme: mloberg/strata-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
