author: Sebastián RIFFO
title: Sebastián RIFFO
email: sebastianreyesr@gmail.com

locals: 
  es: 
    description: Matemático aplicado
    position: Investigador postdoctoral
  en: 
    description: Applied Mathematician
    position: Postdoctoral researcher
institution: IPSL (Sorbonne Université)

github_username: sebastianriffo
linkedin_username: sriffo
twitter_username: ~
dribbble_username: ~
facebook_username: ~
flickr_username: ~
instagram_username: ~
pinterest_username: ~
youtube_username: ~
googleplus_username: ~
rss: false

show_excerpts: true
date_format: "%b %-d, %Y"

# logo: https://picsum.photos/123?image=669

# Build settings
# theme: jekyll-theme-strata
# remote_theme: mloberg/strata-jekyll-theme
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
