title: Your awesome title
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: mloberg
github_username: mloberg
dribbble_username: ~
facebook_username: ~
flickr_username: ~
instagram_username: mloberg
linkedin_username: ~
pinterest_username: ~
youtube_username: ~
googleplus_username: ~
rss: true

show_excerpts: true
date_format: "%b %-d, %Y"

logo: https://picsum.photos/123?image=669

# Build settings
# theme: jekyll-theme-strata
# remote_theme: mloberg/strata-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
